Update publishing steps in readme
DevCycleHQ/cli pull request #92
Opened 2022-11-07 18:56 UTC by laurawarr

2022-11-07 18:59 UTC, ajwootto requested changes
we shouldnt have a package-lock.json here

2022-11-07 19:02 UTC, laurawarr commented
> we shouldnt have a package-lock.json here

how did those sneak in 👀

2022-11-07 19:03 UTC, ajwootto commented
> > we shouldnt have a package-lock.json here
> 
> how did those sneak in 👀

most likely because you ran commands via `npm` instead of `yarn`

2022-11-08 15:57 UTC, ajwootto approved these changes

2022-11-08 16:04 UTC, merged